version: '3.8'

networks:
  testnetworks:
    driver: bridge

services:
  postgres:
    container_name: postgresForDibiai
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QWEasd123
      POSTGRES_DB: testDB
    ports:
      - "13470:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - testnetworks

volumes:
  dbdata: